#!/bin/bash

function declareConstants() {
    $1 PACKAGES_DIR "$HOME/Documents/Documents/Latex Templates/Packages"
    $1 TEMPLATES_DIR "$HOME/Documents/Documents/Latex Templates/Templates"
    $1 IDENTITIES_DIR "$HOME/Documents/Documents/Latex Templates/Identities"
    $1 MODULES "$SCRIPT_LIB/latex_modules"
}

function printHelp() {
    cat << EOF

    Create and build latex documents.
EOF

    for module in "$MODULES/"*; do
        local moduleName=$(basename "$module")

        echo
        echo
        echo -n "      ${PROGNAME} "
        echoGreen "$moduleName " -n

        source "$module"
        module_print_help
    done
}

function loadOptions() {
    unusedBehaviour="IGNORE"
    return 0
}

# 1: Suggested document name
function selectMainFile() {
    if [ $# -eq 1 ] && [ "$1" != "" ]; then
        mainTexFile="$1"
    else

        local texFiles=()

        for file in *; do
            if [ -f "$file" ] && [[ "$file" == *.tex ]]; then
                texFiles+=("$file")
            fi
        done

        if [ ${#texFiles[@]} -eq 0 ]; then
            error "No document file found"
        elif [ ${#texFiles[@]} -eq 1 ]; then
            mainTexFile="${texFiles[0]}"
        else
            bodyFound=false
            for texFile in "${texFiles[@]}"; do
                if [[ "$texFile" == *_body.tex ]]; then
                    bodyFound=true
                    mainTexFile="${texFile%_body.tex}"
                fi
            done
            $bodyFound || error "Specify a document file"
        fi
    fi

    if [[ "$mainTexFile" != *".tex" ]]; then
        mainTexFile="${mainTexFile}.tex"
    fi

    test -f "$mainTexFile" || error "File $mainTexFile does not exist"
}

function run () {
    hasMoreArgs $#

    local module="$MODULES/$1"

    if [ ! -f "$module" ]; then
        error "Unknown mode: $1"
    fi


    source "$module"
    shift
    ARGUMENTS=("$@")
    module_load_options

    if [ $unusedBehaviour != "IGNORE" ]; then
        checkUnused
    fi

    module_run "${ARGUMENTS[@]:+${ARGUMENTS[@]}}"
}

source "$SCRIPT_LIB/scriptStarter"
