#!/bin/bash
function module_print_help() {
    cat << EOF
`echoViolet "[templates|packages|identities]"`

        List the available templates or packages
EOF
}

function module_load_options() {
    return 0
}

function module_run() {
    local list="${1:-templates}"
	local directory

	if [ "$list" == "templates" ]; then
		directory="$TEMPLATES_DIR"
	elif [ "$list" == "packages" ]; then
		directory="$PACKAGES_DIR"
	elif [ "$list" == "identities" ]; then
		directory="$IDENTITIES_DIR"
	else
		error "Wrong argument: $1"
	fi

	for file in "$directory/"*; do
        # test -f "$file" && echo -e "[\033[01;34m `basename "${file%.*}"` \033[0m]"
        local fileName="$(basename "$file")"
        fileName="${fileName,,}"
		test -f "$file" && echo -n "${fileName%.*} "
    done
	echo
}
