#!/bin/bash

function printHelp() {
    cat << EOF

    Flatten the folder structure. This will move all files in all subdirectories in this directory.
    The subdirectories will not be deleted, but will remain empty.

    In case of name conflict, a new name is generated for duplicates.

    `echoGreen Usage:` ${PROGNAME} `echoViolet [/directory]`

        `echoViolet directory` : Directory to flatten (default: current directory)
EOF
}

function declareConstants() {
    return 0
}

function loadOptions() {
    # unusedBehaviour="IGNORE"
    return 0
}

function process() {
    for file in "$1/"*; do
        if [ -f "$file" ]; then
            local name=$(findName "$file")

            mv "$file" "$name"
        elif [ -d "$file" ]; then
            process "$file"
        fi
    done
}

function findName() {
    local filename=$(basename "$1")

    local extension="${filename##*.}"
    local name="${filename%.*}"
    local i=1

    while [ -f "$dir/$filename" ]; do
        i=$((i+1))
        filename="${name}_$i.$extension"
    done

    echo "$filename"
}

function run () {
    if [ $# -eq 1 ]; then
        dir="$1"
        test -d "$1" || error "Not a directory"
    else
        dir="."
    fi

    for file in "$dir/"*; do
        if [ -d "$file" ]; then
            process "$file"
        fi
    done
    return 0
}

source "$SCRIPTS_HELPERS/scriptStarter"
