#!/bin/bash

function printHelp() {
    cat << EOF

    Manage scripts

    `echoGreen Usage:` ${PROGNAME} `echoBlue "[action] [target]"` `echoViolet [OPTIONS]`

        `echoBlue action`
            `echoBlue pull`  : Pull the latest changes
            `echoBlue setup` : Run the setup script
            `echoBlue create`: Create a new script in the path directory
            `echoBlue user`  : Open a user config file

EOF
}

function declareConstants() {
    $1 EDITOR "xdg-open"
    return 0
}


function loadOptions() {
    unusedBehaviour="IGNORE"
    # TODO Allow to pass password from stdin
    READONLY=false getOpt "--stdout" useStdout
    READONLY=false getOpt "-o|--output" output 1 ""
    return 0
}


function create() {
    error "Not implemented yet"
}

function pull() {
    git pull
    if [ -d .jsync ]; then
        jsync sync
    fi
}

function setup() {
    if [ $# -gt 0 ]; then
        local script="$1"
        shift

        . "$SCRIPTS_HELPERS/setup.c/$script" "$@"
    else
        ./setup.sh
    fi
}

function user() {
    if [ $# -eq 0 ]; then
        target="config.properties"
    else
        target="$1"
    fi

    target="${SCRIPTS_DATA}/$target"
    test -f "$target" || error "File not found: $target"
    $EDITOR "$target"
}

function run () {
    cd "$SCRIPTS/.."

    getArg action
    if ! [[ "$action" =~ ^(pull|setup|create|user)$ ]]; then
        error "Mode must be one of: pull,setup, user or create"
    fi

    shift
    $action "$@"
}

source "$SCRIPTS_HELPERS/scriptStarter"
