#!/bin/bash
function printHelp() {
    cat << EOF

    Simple script to move files to a specifc trash directory.

    `echoGreen Usage` ${PROGNAME} `echoBlue [files...]`

    Use it with `echoViolet "--restore"` to a restore some file.
EOF
}

function declareConstants() {
	$1 TRASH_DIR "__TRASH__.__TRASH_DIR__"
}

function loadOptions() {
	# unusedBehaviour="IGNORE"
    getOpt "--restore" restore
	return 0
}

function run () {
	if [ ! -d "$TRASH_DIR" ]; then
		mkdir "$TRASH_DIR" || error "Cannot create directory $TRASH_DIR"
	fi

    if $restore; then
        TARGET_DIRECTORY="$TRASH_DIR" cLastFile -m -i

    elif [ $# -eq 0 ]; then
		echo "$TRASH_DIR"

	else
        for file in "$@"; do
            if [ -e "$file" ]; then
                getFreshFile destination "$TRASH_DIR/$(basename "$file")"
                mv "$file" "$destination"
            else
                echoYellow "[warning] File not found, skipping $file"
            fi
        done
    fi
}

source "$SCRIPTS_HELPERS/scriptStarter"
