#!/bin/bash


find() {
    local tmp
    # tmp=`wmctrl -l -x | grep -Eow "[^ ]*  $2 $1 [^ ]* .*$3"` || return 1
    wmctrl -l -x | grep -Eow "[^ ]*  $2 $1 [^ ]* .*$3" | while read -r line ; do
        echo "$line" | head -c 10 && echo
        # your code goes here
    done
    # echo "$tmp" | head -c 10
}

if [ $# -eq 0 ]; then
    echo "Usage: findWindow <CLASS> </DESKTOP> </TITLE>" 1>&2
    exit 1
fi
find "$1" "${2:-[0-9]}" "${3:-.*}"
