#!/usr/bin/env bash
function error() {
    echo "$@"
    exit 1
}




# function gclonecd() {
#     local dir=`echo "$1" | sed -n -e 's/^.*\/\([^.]*\)\(.git\)*/\1/p'`
#     test -d "$dir" || git clone "$1"
#     cd "$dir"
# }

function projectName() {
    echo "$1" | sed -n -e 's/^.*\/\([^.]*\)\(.git\)*/\1/p'
}

test $# -eq 2 || error "Usage: install_repo <git_url> <destination>"

GIT_URL="$1"
DESTINATION="$2"
PROJECT_NAME="$(projectName "$1")"

if [ -d "$DESTINATION/$PROJECT_NAME" ]; then
    pushd "$DESTINATION/$PROJECT_NAME" > /dev/null
    git pull
else
    git clone "$GIT_URL" "$DESTINATION/$PROJECT_NAME"
    pushd "$DESTINATION/$PROJECT_NAME" > /dev/null
fi

if [ -d ".jsync" ]; then
    jsync sync
fi

for installer in "$SCRIPT_LIB/modules/install_modules/installers/"*; do
    if $installer isCompatible; then
        test -d "$SCRIPT_LAUNCHER" || mkdir "$SCRIPT_LAUNCHER" || error "Cannot create $SCRIPT_LAUNCHER"

        PROJECT_NAME="$PROJECT_NAME" $installer install || error "Failed to compile project"
        PROJECT_NAME="$PROJECT_NAME" $installer copyToBin || error
        PROJECT_NAME="$PROJECT_NAME" $installer createLauncher || error

        exit 0
    fi
done

error "Unrecognised project type: $PWD"
